In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: ignored

In [6]:
data = pd.read_csv('Diabetes_Prediction.csv')

In [7]:
df1 = data

In [8]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [9]:
df1.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [10]:
#checking 0 values in every predictor
z = df1['Pregnancies'].value_counts()[0]
print (f' number of 0 in Pregnacies:  {z}')
z = df1['Glucose'].value_counts()[0]
print (f' number of 0 in Glucose:  {z}')
z = df1['BloodPressure'].value_counts()[0]
print (f' number of 0 in BloodPressure:  {z}')
z = df1['SkinThickness'].value_counts()[0]
print (f' number of 0 in SkinThickness:  {z}')
z = df1['Insulin'].value_counts()[0]
print (f' number of 0 in Insulin:  {z}')
z = df1['BMI'].value_counts()[0]
print (f' number of 0 in BMI:  {z}')

 number of 0 in Pregnacies:  111
 number of 0 in Glucose:  5
 number of 0 in BloodPressure:  35
 number of 0 in SkinThickness:  227
 number of 0 in Insulin:  374
 number of 0 in BMI:  11


In [11]:
df1.loc[df1['Insulin'] == 0, 'Insulin'] = df1['Insulin'].median()

In [12]:
df1.loc[df1['Glucose'] == 0, 'Glucose'] = df1['Glucose'].median()

In [13]:
df1.loc[df1['BloodPressure'] == 0, 'BloodPressure'] = df1['BloodPressure'].median()

In [14]:
df1.loc[df1['SkinThickness'] == 0, 'SkinThickness'] = df1['SkinThickness'].median()

In [15]:
df1.loc[df1['BMI'] == 0, 'BMI'] = df1['BMI'].median()

In [16]:
df1.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  121.656250      72.386719      27.334635   94.652344   
std       3.369578   30.438286      12.096642       9.229014  105.547598   
min       0.000000   44.000000      24.000000       7.000000   14.000000   
25%       1.000000   99.750000      64.000000      23.000000   30.500000   
50%       3.000000  117.000000      72.000000      23.000000   31.250000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    32.450911                  0.471876   33.240885    0.348958  
std      6.875366                  0.331329   11.760232    0.476951  
min     18.200000                  0.078000   21.000000    0.000000  
25%     27.500000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler
sc = RobustScaler()

X = df1.iloc[:, :-1].values
X  = sc.fit_transform(X)
y = df1.iloc[:, -1].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)


In [25]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler
sc = RobustScaler()

X = df1.iloc[:, :-1].values

sc.fit(X)
X = sc.transform(X)

# X  = sc.fit_transform(X)
y = df1.iloc[:, -1].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)


In [26]:
X

array([[ 0.6       ,  0.7654321 ,  0.        , ...,  0.17582418,
         0.66535948,  1.23529412],
       [-0.4       , -0.79012346, -0.375     , ..., -0.59340659,
        -0.05620915,  0.11764706],
       [ 1.        ,  1.62962963, -0.5       , ..., -0.95604396,
         0.78300654,  0.17647059],
       ...,
       [ 0.4       ,  0.09876543,  0.        , ..., -0.63736264,
        -0.33333333,  0.05882353],
       [-0.4       ,  0.22222222, -0.75      , ..., -0.20879121,
        -0.06143791,  1.05882353],
       [-0.4       , -0.59259259, -0.125     , ..., -0.17582418,
        -0.1503268 , -0.35294118]])

In [27]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state = 42)
X_train_os, y_train_os = smote.fit_resample(X_train, y_train)
np.array(np.unique(y_train_os, return_counts=True)).T

array([[  0, 401],
       [  1, 401]])

In [28]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, accuracy_score
RFC = RandomForestClassifier(bootstrap=False, ccp_alpha=0.0,
                            class_weight='balanced_subsample',
                            criterion='entropy', max_depth=6,
                            max_features='sqrt',
                            max_leaf_nodes=None, max_samples=None,
                            min_impurity_decrease=0.005,
                            min_samples_leaf=5, min_samples_split=9,
                            min_weight_fraction_leaf=0.0,
                            n_estimators=110, n_jobs=-1,
                            oob_score=False, random_state=5218,
                            verbose=0, warm_start=False)
RFC.fit(X_train_os, y_train_os)
RFC_pred = RFC.predict(X_test)
print(classification_report(y_test,RFC_pred))
cm = confusion_matrix(y_test, RFC_pred)
print('----------------------------------------------------')
print(cm)
accuracy_score(y_test, RFC_pred)

              precision    recall  f1-score   support

           0       0.87      0.80      0.83        99
           1       0.68      0.78      0.73        55

    accuracy                           0.79       154
   macro avg       0.78      0.79      0.78       154
weighted avg       0.80      0.79      0.79       154

----------------------------------------------------
[[79 20]
 [12 43]]


0.7922077922077922

In [29]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
kfold = KFold(n_splits=10)
results = cross_val_score(RFC, X, y, cv=kfold)
print("Accuracy: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))


Accuracy: 76.17% (4.06%)


In [30]:
import pickle
pickle.dump(RFC, open('randomforest_old_method.pkl', 'wb'))

In [31]:
pickle.dump(sc, open('sklearn.pkl', 'wb'))

In [32]:
pd.DataFrame(X_test)

0         1      2         3         4         5         6         7
0    0.8  0.469136  0.125  0.333333  1.072351 -0.659341  0.717647  1.294118
1   -0.4  0.839506 -0.750  0.000000 -0.007752 -0.648352 -0.505882 -0.411765
2    0.6 -0.197531 -0.750  0.444444 -0.007752 -0.769231 -0.435294 -0.117647
3    0.0 -1.382716  0.625  0.555556 -0.007752  0.263736 -0.338562  1.000000
4   -0.4 -0.024691  0.375  0.666667  1.537468  0.450549  0.322876 -0.235294
..   ...       ...    ...       ...       ...       ...       ...       ...
149  0.6 -0.444444 -0.750 -0.444444  0.235142 -0.560440  0.325490  0.176471
150  0.0 -0.049383 -0.375  1.777778  1.124031  0.670330 -0.581699 -0.058824
151  1.0  1.753086  0.375  0.000000 -0.007752  1.747253 -0.615686  0.823529
152  0.4  0.469136  0.625  0.000000 -0.007752  0.000000  0.699346  2.352941
153  0.2 -0.666667  0.000  0.000000 -0.007752 -0.439560  0.620915  0.117647

[154 rows x 8 columns]

In [33]:
from flask import Flask
from flask import jsonify, request
from datetime import datetime
from flask_ngrok import run_with_ngrok
from pycaret.anomaly import *


app = Flask(__name__)
run_with_ngrok(app)

@app.route('/', methods=['GET'])
def index():
  return jsonify({"Nama":"Farah Y"})

@app.route('/predict', methods=['GET'])
def result():
  data = request.json
  df = pd.DataFrame(data, index=[0])
 
  
  print(df.dtypes)

  with open('randomforest_old_method.pkl','rb') as file:
     Lin_reg_model = pickle.load(file)

  # prediction = Lin_reg_model.predict(df)
  prediction = Lin_reg_model.predict(df)
  print(df)
  print(prediction)
  data['Prediction'] = prediction[0]
  # data['Datetime'] = datetime.now().strftime('%Y-%m-%d')

  with open('data_collection.txt','a') as file:
    file.write("%s\n" % data)

  return jsonify({"Status":"Berhasil", "prediction":str(prediction[0])})


if __name__ == "__main__":
  app.run()

ModuleNotFoundError: ignored